# Generated by Django 3.1.7 on 2021-03-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvhome',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rvhome',
            old_name='body',
            new_name='specification',
        ),
    ]
